public class Util {
    public static DiscountConst DISCOUNT {
        get {
            return new DiscountConst();
        }
    }
    public static SettingsConst SETTINGS {
        get {
            return new SettingsConst();
        }
    }
    public static OrderConst ORDER {
        get {
            return new OrderConst();
        }
    }
    public static ProductConst PRODUCT {
        get {
            return new ProductConst();
        }
    }
    public static ProductSyncQueueConst PRODUCT_SYNC_QUEUE {
        get {
            return new ProductSyncQueueConst();
        }
    }
    public static TestConst TEST {
        get {
            return new TestConst();
        }
    }
    public static EmailConst EMAIL {
        get {
            return new EmailConst();
        }
    }
    public static ComplaintConst COMPLAINT {
        get {
            return new ComplaintConst();
        }
    }
}
