public class Util {
    public static DiscountConst DISCOUNT { get { return new DiscountConst(); } }
    public static SettingsConst SETTINGS { get { return new SettingsConst(); } }
    public static OrderConst ORDER { get { return new OrderConst(); } }
    public static ProductConst PRODUCT { get { return new ProductConst(); } }
    public static ProductSyncQueueConst PRODUCT_SYNC_QUEUE { get { return new ProductSyncQueueConst(); } }
}