name: Validate PR on Salesforce

on:
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth_url.txt
          sf org login sfdx-url -f auth_url.txt -a ci-org
          rm auth_url.txt # Clean up the file for security

      - name: Validate Source
        run: sf project deploy start --source-dir force-app --target-org ci-org --dry-run --test-level RunLocalTests